url: https://thomasandkaren.us
baseurl: /wedding

# Site settings
title: '#TKWedding'
email: tk@thomasandkaren.us
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Karen E. Robinson
  pic: IMG_20170528_164420_square
  position: The Smart One
  social:
    - title: twitter
      url: //twitter.com/kerobinso
    - title: facebook
      url: //facebook.com/karenerobinson
    - title: stack-overflow
      url: #

- name: Thomas Garner
  pic: 7b750a5d0b7873c1ce8fadbbff6910d4
  position: The Other One
  social:
    - title: twitter
      url: //twitter.com/thomas536
    - title: facebook
      url: //facebook.com/thomas536
    - title: linkedin
      url: //linkedin.com/in/thomas536

# Social networks usernames (many more available: google-plus, flickr, dribbble pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/tkwedding
  - title: facebook
    url: http://facebook.com/tkwedding
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/tkwedding
  - title: github
    url: http://github.com/tkwedding

# Postal address (add as many lines as necessary)
address:
  - line: 28 Devonshire Ave Apt D
  - line: Mountain View, CA 94043

# Build settings
markdown: kramdown
permalink: pretty
